import RecyclingServiceAccordion from '@/components/RecyclingServiceAccordion'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hounslow Recycling Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RecyclingServiceAccordion
          title="Lorem ipsum"
          description="Lorem ipsum something something"
          content="Lorem ipsum x 100"
        />
        <RecyclingServiceAccordion
          title="Lorem ipsum but different"
          description="Lorem ipsum but different something something"
          content="Lorem ipsum but different x 100"
        />
        <RecyclingServiceAccordion
          title="Lorem ipsum the third"
          description="Lorem ipsum the third something something"
          content="Lorem ipsum the third x 100"
        />
      </main>
    </>
  )
}
